"""Update payload in outboxevent table

Revision ID: 00c97bd0cc8f
Revises: bee71907f74e
Create Date: 2025-12-07 15:51:55.974570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00c97bd0cc8f'
down_revision: Union[str, None] = 'bee71907f74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outboxevent', 'aggregate_id')
    op.add_column('product', sa.Column('entity_version', sa.Integer(), nullable=False))
    op.add_column('producttype', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('producttype', sa.Column('entity_version', sa.Integer(), nullable=False))
    op.drop_column('producttype', 'type_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producttype', sa.Column('type_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('producttype', 'entity_version')
    op.drop_column('producttype', 'name')
    op.drop_column('product', 'entity_version')
    op.add_column('outboxevent', sa.Column('aggregate_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
