"""db configuration

Revision ID: bee71907f74e
Revises: 
Create Date: 2025-09-29 23:44:24.960738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bee71907f74e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outboxevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='aggregatetype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRYING', name='queuestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outboxevent_id'), 'outboxevent', ['id'], unique=False)
    op.create_table('producttype',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producttype_id'), 'producttype', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_type_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_type_id'], ['producttype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_price'), 'product', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_price'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_producttype_id'), table_name='producttype')
    op.drop_table('producttype')
    op.drop_index(op.f('ix_outboxevent_id'), table_name='outboxevent')
    op.drop_table('outboxevent')
    # ### end Alembic commands ###
